server:
  port: 8080
  session:
    timeout: 30
  context-path: /tdzmxjz
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&charaterEncoding=utf-8
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
  #httpcode
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
#mybatisPath
mybatis:
  type-aliases-package: com.tdzmxjz.entity
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config
#logging
logging:
  config:
  level: debug




